INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O Cortiço', 'Aluísio Azevedo', 'Sextante', '110', '', '1976', 'Não Lido', 'Diego', 'Young Adult Fiction', 'pt-BR', '2024-07-20');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Harry Potter e a Pedra Filosofal', 'J. K. Rowling', 'Rocco', '263', 'Lia Wyler', '2000', 'Lido', 'Hugo', 'Fiction', 'pt-BR', '2023-01-17');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Harry Potter e a Câmara Secreta', 'J. K. Rowling', 'Rocco', '287', 'Lia Wyler', '2001', 'Lido', 'Hugo e Diego', 'Juvenile Fiction', 'pt-BR', '2015-12-08');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Harry Potter e o Cálice de Fogo', 'J. K. Rowling', 'Rocco', '583', 'Lia Wyler', '2002', 'Lido', 'Hugo e Diego', 'Adventure stories', 'pt-BR', '2002');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Harry Potter e o Prizioneiro de Azkaban', 'J. K. Rowling', 'Rocco', '348', 'Lia Wyler', '2002', 'Lido', 'Diego', 'Adventure stories', 'pt-BR', '2002');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Meu Pé de Laranja Lima', 'José Mauro de Vasconcelos', 'Melhoramentos', '193', '', '2002', 'Lido', 'Diego', 'Unknown', 'pt-BR', '2013-03-26');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Amor não tem cor', 'Giselda Laporta Nicolelis', 'FT', '111', '', '2006', 'Não Lido', 'Diego', 'Unknown', 'pt-BR', '2002');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Auto da Compadecida', 'Ariano Suassuna', 'Agir', '186', '', '2006', 'Lido', 'Diego', 'Drama', 'pt-BR', '2024-11-21');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Memórias póstumas de Brás Cubas', 'Machad de Assis', 'Editora Moderna', '152', '', '2006', 'Lido', 'Diego', 'Fiction', 'pt', '2024-06-28');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O Fantasma de Canterville - Uma novela e três contos', 'Oscar Wilde', 'Editora Scipione', '105', 'Rubem Braga', '2006', 'Não Lido', 'Diego', 'Fiction', 'pt-BR', '2021-07-30');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O Grande Mentecapto', 'Fernando Sabino', 'Record', '251', '', '2006', 'Lido', 'Murillo', 'Fiction', 'pt-BR', '2020-06-29');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Ponciá Vicêncio', 'Conceição Evaristo', 'Companhia das Letras', '84', '', '2006', 'Não Lido', 'Hugo', 'Fiction', 'pt-BR', '2020-08-10');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Senhora', 'José de Alencar', 'Afiliada', '236', '', '2006', 'Não Lido', 'Diego', 'Unknown', 'pt-BR', '2010');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('26 Poetas Hoje', 'Heloisa Buarque de Hollanda', 'Aeroplano', '270', '', '2007', 'Não Lido', 'Diego', 'Poetry', 'pt-BR', '2021-02-24');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Maira', 'Darcy Ribeiro', 'Record', '425', '', '2007', 'Não Lido', 'Diego', 'Fiction', 'en', '1984');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O recado do Morro', 'João Guimarães Rosa', 'Nova Fronteira', '127', '', '2007', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2013-09-18');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Prosas seguidas de odes mínimas', 'José Paulo Paes', 'Maza Edições', '132', '', '2007', 'Não Lido', 'Diego', 'Poetry', 'pt-BR', '1992');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('A vida, o universo e tudo mais', 'Douglas Adams', 'Sextante', '229', 'Carlos Irineu da Costa', '2008', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2010-11-09');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Até mais, e obrigado pelos peixes!', 'Douglas Adams', 'Sextante', '203', 'Marcia Heloisa Amarante Gonçalves', '2008', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2010-11-09');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O Guia do Mochilero das Galáxias', 'Douglas Adams', 'Sextante', '204', 'Paulo Fernandes Henriques
Brito e Carlos Irineu da Costa', '2008', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2010-11-09');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O Restaurante no fim do Universo', 'Douglas Adams', 'Sextante', '221', 'Carlos Irineu da Costa', '2008', 'Lido', 'Diego', 'Unknown', 'pt-BR', '2022-10-10');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Antes do Baile Verde', 'Lygia Fagundes Telles', 'Rocco', '159', '', '2009', 'Lido', 'Hugo', 'Fiction', 'pt-BR', '2009-04-23');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Bastardos Inglórios', 'Quentin Tarantino', 'Amarilys', '156', 'Anna Lim', '2009', 'Lido', 'Diego', 'Unknown', 'Unknown', 'Unknown');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Cobra Norato', 'Raul Bopp', 'José Olympio Editora', '57', '', '2009', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2016-11-25');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Cônica da casa assassinada', 'Lúcio Cardoso', 'Civilização Brasileira', '517', '', '2009', 'Lido', 'Diego', 'Literary Criticism', 'pt-BR', '1991');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Laços de Família', 'Clarice Lispector', 'Rocco', '135', '', '2009', 'Lido', 'Hugo', 'Fiction', 'pt-BR', '2020-06-19');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Os da minha rua', 'Ondjaki', 'Língua Geral', '159', '', '2009', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2010-09-30');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Sermões Escolhidos', 'Padre Antônio Vieira', 'Martin Claret', '221', '', '2009', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2023-12-22');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Uma vida em Segredo', 'Autran Dourado', 'Rocco', '131', '', '2009', 'Não Lido', 'Deigo', 'Unknown', 'pt-BR', '1983');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('A arte da Guerra', 'Sun Tzu', 'Jardim dos Livros', '125', 'André da Silva Bueno', '2010', 'Lido', 'Diego', 'Literary Collections', 'pt-BR', '2014-02-05');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Através do Espelo e o que Alice encontrou por lá', 'Lewis Carrol', 'Zahar', '168', 'Maria Luiza X. de A. Borges', '2010', 'Lido', 'Diego', 'Antiques & Collectibles', 'pt-BR', '2024-12-01');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Aventuras de Alice no país das maravilhas', 'Lewis Carrol', 'Zahar', '149', 'Maria Luiza X. de A. Borges', '2010', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2016');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O Iluminado', 'Stephen King', 'Objetiva', '313', 'Betty Ramos de Albuquerque', '2010', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2017-08-22');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('A Fúria dos Reis', 'George R. R. Martin', 'Leya', '648', '', '2012', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2019-04-23');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('A Guerra dos Tronos', 'George R. R. Martin', 'Leya', '592', '', '2012', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2019-03-25');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('A Tormenta das Espadas', 'George R. R. Martin', 'Leya', '880', 'Jorge Candeias', '2012', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2019-04-23');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O Festim dos Corvos', 'George R. R. Martin', 'Leya', '641', 'Jorge Candeias', '2012', 'Lido', 'Deigo', 'Fiction', 'pt-BR', '2019-11-11');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('A Dance with Dragons', 'George R. R. Martin', 'Bantam Books', '1112', '', '2013', 'Lido', 'Diego', 'Fiction', 'en', '2011');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('A menina que roubava Livros', 'Markus Zusak', 'Intrínseca', '480', 'Vera Ribeiro', '2013', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2012-11-13');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('A Dança dos Dragões', 'George R. R. Martin', 'Leya', '854', 'Marcia Blasques', '2014', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2020-03-25');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Contos Inacabados', 'J. R. R. Tolkien', 'Martin Fontes', '585', 'Ronald Eduard Kyrmse', '2016', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2024-07-15');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Deuses Americanos', 'Neil Gaiman', 'Intrínseca', '574', 'Leonardo Alves', '2016', 'Lido', 'Diego', 'Bodyguards', 'pt-BR', '2019');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Mitologia Nórdica', 'Neil Gaiman', 'Intrínseca', '286', 'Edmundo Barreiros', '2017', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2017-03-13');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Morte no Nilo', 'Agatha Christie', 'Harper Colins', '248', 'Newton Goldman', '2017', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2015-04-17');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O Assassinato No Expresso Oriente', 'Agatha Christie', 'Harper Colins', '196', 'Archibaldo Figueira', '2017', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2014-04-15');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O Caso de Charles Dexter Ward', 'H. P. Lovecraft', 'L&MP', '173', 'Ana Maria Capovilla', '2017', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2025-03-22');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O oceano no fim do caminho', 'Neil Gaiman', 'Intrínseca', '205', 'Renata Pettengill', '2017', 'Lido', 'Diego', 'Young Adult Fiction', 'pt-BR', '2024-02-05');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Os meninos da Rua Paulo', 'Ferenc Molnár', 'Companhia das Letras', '251', 'Paulo Rónai', '2017', 'Lido', 'Diego', 'Young Adult Fiction', 'pt-BR', '2023-05-02');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Um corpo na Biblioteca', 'Agatha Christie', 'Harper Colins', '180', 'Edilson Alkimin Cunha', '2017', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2015-01-15');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('A História da Mitologia para quem tem pressa', 'MArk Daniels', 'Valentina', '196', 'Heloísa Leal', '2018', 'Lido', 'Solange', 'History', 'pt-BR', '2015-12-01');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('A Náusea', 'Jean-Paul Sartre', 'Nova Fronteira', '199', 'Rita Braga', '2018', 'Não Lido', 'Diego', 'Unknown', 'pt-BR', '2006');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Astrofísica para Apressados', 'Neil DeGrasse Tyson', 'Planeta', '179', 'Alexandre Martin', '2018', 'Lido', 'Diego', 'Science', 'pt', '2017-08-01');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Buracos Negros', 'Stephen Hawking', 'Intrínseca', '62', 'Cássio de Arantes Leite', '2018', 'Lido', 'Nina', 'Science', 'pt-BR', '2017-01-26');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Cosmos', 'Carl Sagan', 'Companhia das Letras', '487', 'Paluo Geiger', '2018', 'Lido', 'Diego', 'Science', 'en', '2011-07-06');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O gigante enterrado', 'Kazuo Ishiguro', 'Companhia das Letras', '396', 'Sonia Moreira', '2018', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2015-06-12');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O inverno dos escritores mortos', 'Miller Britto', '', '287', '', '2018', 'Lido', 'Diego', 'Unknown', 'Unknown', 'Unknown');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Tropas Estrelares', 'Robert A. Heinlein', 'Aleph', '364', 'Carlos Augusto', '2018', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2015-10-28');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Um Estranho numa terra estranha', 'Robert A. Heinlein', 'Aleph', '569', 'Edmo Suassuna', '2018', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2017-03-24');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Uma Breve história do tempo', 'Stephen Hawking', 'Intrínseca', '255', 'Cássio de Arantes Leite', '2018', 'Lido', 'Diego', 'Science', 'pt-BR', '2015-01-13');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('A Trilogia Dupin', 'Edgar Allan Poe', 'LGE Editora', '152', 'Marcius Souza', '2019', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2020-05-06');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Harry Potter e a Ordem da Fênix', 'J. K. Rowling', 'Rocco', '703', 'Lia Wyler', '2019', 'Lido', 'Diego', 'Hogwarts School of Witchcraft and Wizardry (Imaginary organization)', 'pt-BR', '2003');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Harry Potter e as Relíquias da Morte', 'J. K. Rowling', 'Rocco', '551', 'Lia Wyler', '2019', 'Lido', 'Diego', 'Unknown', 'gl', '2008-02-21');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Harry Potter e o Enigma do Príncipe', 'J. K. Rowling', 'Rocco', '471', 'Lia Wyler', '2019', 'Lido', 'Diego', 'Juvenile Fiction', 'pt-BR', '2015-12-08');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Não me abandone jamais', 'Kazuo Ishiguro', 'Companhia das Letras', '343', 'Beth Vieira', '2019', 'Lido', 'Nina', 'Fiction', 'pt-BR', '2005-10-04');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Neuromancer', 'William Gibson', 'Aleph', '319', 'Fábio Fernandes', '2019', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2015-09-16');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O Livro do Cemitério', 'Neil Gaiman', 'Rocco Jovens Leitores', '335', 'Ryta Vinagre', '2019', 'Lido', 'Diego', 'Young Adult Fiction', 'pt-BR', '2018-06-04');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O universo numa casca de noz', 'Stephen Hawking', 'Intrínseca', '223', 'Cássio de Arantes Leite', '2019', 'Lido', 'Diego', 'Science', 'pt-BR', '2016-02-01');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('As mais belas lendas da Idade Média', 'Laurence Camiglieri
Marcelle Huisman
Georges Huisman', 'Martins Fontes', '309', 'Mônica Stabel', '2020', 'Lido', 'Diego', 'Unknown', 'pt-BR', '2001');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Barba ensopada de sangue', 'Daniel Galera', 'Companhia das Letras', '422', '', '2020', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2012-11-05');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Coraline', 'Neil Gaiman', 'intrínseca', '223', 'Bruna Beber', '2020', 'Lido', 'Diego', 'Young Adult Fiction', 'pt-BR', '2020-06-19');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Flores para Algernon', 'Daniel Keyes', 'Aleph', '284', 'Luisa Geisler', '2020', 'Lido', 'Hugo', 'Fiction', 'pt-BR', '2018-07-10');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Jackob, o mentiroso', 'Jurek Becker', 'Companhia de bolso', '253', 'José Marcos Mariani de Macedo', '2020', 'Lido', 'Diego', 'Unknown', 'pt-BR', '2022');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Labirinto do Fauno', 'Guillermo del Torro
Cornelia Funke', 'Intrínseca', '314', 'Bruna Beber', '2020', 'Lido', 'Diego', 'Fiction', 'pt', '2019-07-10');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Metrópolis', 'Thea Von Harbou', 'Aleph', '458', 'Petê Rissatti', '2020', 'Lido', 'Diego', 'Fiction', 'en', '2021-03-23');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O Demônio na Cidade Branca', 'Erik Larson', 'intrínseca', '437', 'Berilo Vargas', '2020', 'Lido', 'Diego', 'History', 'pt-BR', '2016-07-12');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O Perfume', 'Patrick Süskinf', 'BestBolso', '271', 'Flávio R. Kothe', '2020', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2022-10-03');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Os Filhos de Húrin', 'J. R. R. Tolkien', 'Harper Collins', '283', 'Ronald Eduard Kyrmse', '2020', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2020-02-17');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Um amor incômodo', 'Elena Ferrante', 'intrínseca', '173', 'Marcello Lino', '2020', 'Não Lido', 'Diego', 'Fiction', 'pt-BR', '2017-03-20');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Arsène Lupin contra Herlock Sholmes', 'Maurice Leblanc ', 'Principis', '222', 'Luciene Ribeiro dos Santos', '2021', 'Não Lido', 'Diego', 'Fiction', 'pt-BR', '2021-03-01');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Arsène Lupin o ladrão de casaca', 'Maurice Leblanc ', 'Principis', '192', 'Luciene Ribeiro dos Santos', '2021', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2021-06-29');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Duna', 'Frank Herbert', 'Aleph', '620', 'Maria do Carmo Zanini', '2021', 'Lido', 'Diego', 'Fiction', 'pt', '2015-09-16');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Encontro com Rama', 'Arthur C. Clarke', 'Aleph', '286', 'Susana L. de Alexandria', '2021', 'Não Lido', 'Diego', 'Fiction', 'pt-BR', '2015-09-16');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Eu receberia as piores noticias dos seus lindos lábios', 'Marçal Aquino', 'Companhia das Letras', '229', '', '2021', 'Lido', 'Hugo', 'Fiction', 'pt-BR', '2005-10-31');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Eu robo', 'Isaac Asimov', 'Aleph', '302', 'Aline Storto Pereira', '2021', 'Não Lido', 'Hugo e Diego', 'Fiction', 'pt-BR', '2015-09-16');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Fahrenheit 451', 'Ray Bradbury', 'Biblioteca Azul', '180', 'Cid Knipel', '2021', 'Lido', 'Diego', 'Fiction', 'en', '2003-09-23');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Messias de Duna', 'Frank Herbert', 'Aleph', '253', 'Maria do Carmo Zanini', '2021', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2017-06-09');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O chamado de Cthulhu e outros contos', 'H. P. Lovecraft', 'Principis', '240', 'Danielle Sales', '2021', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2020-06-10');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Uma mulher no escuro', 'Raphael Montes', 'Companhia das Letras', '254', '', '2021', 'Lido', 'Diego', 'Unknown', 'pt-BR', '2019-05-31');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Admirável mundo novo', 'Aldous Huxley', 'Biblioteca Azul', '306', 'Vidal de Oliveira', '2022', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2014-03-06');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Deuses Exteriores e Deuses Anciãos', 'H. P. Lovecraft', 'PandorgA', '166', 'Gabriela Perez
Fátima Pinho
Marsley de Marco', '2022', 'Não Lido', 'Diego', 'Unknown', 'Unknown', 'Unknown');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Livro Fenomenal', 'Irmão do Jorel', 'Harper Collins', '189', '', '2022', 'Lido', 'Diego', 'Unknown', 'Unknown', 'Unknown');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O Homem invisível', 'H. G. Wells', 'Zahar', '193', 'Alexandre Barbosa de Souza 
Rodrigo Lacerda', '2022', 'Não Lido', 'Diego', 'Fiction', 'pt-BR', '2017-04-04');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Os Grandes Antigos', 'H. P. Lovecraft', 'PandorgA', '183', 'Gabriela Perez
Fátima Pinho
Marsley de Marco', '2022', 'Não Lido', 'Diego', 'Unknown', 'Unknown', 'Unknown');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Primeiro como tragédia, depois como farsa', 'Slavoj Žižek', 'Boi Tempo', '130', 'Maria Beatriz de Medina', '2022', 'Não Lido', 'Diego', 'Philosophy', 'pt-BR', '2015-10-26');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Serviçais e raças independentes', 'H. P. Lovecraft', 'PandorgA', '111', 'Gabriela Perez
Fátima Pinho
Marsley de Marco', '2022', 'Não Lido', 'Hugo', 'Unknown', 'Unknown', 'Unknown');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Murder at Holly House', 'Denzil Meyrick', 'Penguin', '356', '', '2025', 'Lido', 'Diego', 'Fiction', 'en', '2023-11-09');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('As esganadas', 'Jô Soares', 'Companhia das Letras', '262', '', '', 'Lido', 'Hugo', 'Fiction', 'pt-BR', '2011-10-14');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Crônicas 1', 'Carlos Drummond de Andrade
Fernando Sabino
Paulo Mendes Campos
Rubem Braga', 'Editora Ática', '84', '', '', 'Não Lido', 'Diego', 'Unknown', 'pt-BR', '1982');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Depois daquela viagem ', 'Valéria Piassa Polizzi', 'Editora Ática', '277', '', '', 'Lido', 'Diego', 'Young Adult Fiction', 'pt-BR', '2013');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Extremamente alto & Incrivelmente perto', 'Jonathan Safran Foer', 'Rocco', '360', 'Daniel Galera', '', 'Lido', 'Solange', 'Unknown', 'Unknown', 'Unknown');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Melhores Poemas Mario Quintana', 'Mario Quintana (Edla Van Steen)', 'Global', '120', '', '', 'Não Lido', 'Diego', 'Poetry', 'pt', '2015-09-04');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Nietzsche para estressados', 'Allan Percy', 'Editora Ática', '128', '', '', 'Lido', 'Solange', 'Self-Help', 'pt-BR', '2011-10-17');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O lobo das planices', 'Conn Iggulden', 'Record', '419', 'Alves Calado', '', 'Lido', 'Hugo', 'Unknown', 'Unknown', 'Unknown');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O retrato de Dorian Gray', 'Oscar Wilde', 'Martin Claret', '187', 'Pietro Nassetti', '', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2024-10-24');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O Senhor da Chuva', 'André Vianco', 'Novo Século', '268', '', '', 'Lido', 'Diego', 'Fiction', 'pt-BR', 'Unknown');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('O Senhor do Arco', 'Conn Iggulden', 'Record', '418', 'Alves Calado', '', 'Não Lido', 'Diego', 'Fiction', 'pt-BR', '2022-08-09');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Quadribol através dos séculos', 'J. K. Rowling', 'Rocco', '63', 'Lia Wyler', '', 'Lido', 'Diego', 'Games & Activities', 'pt-BR', '2016-05-09');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Sherlock Holme - O Cão de Baskervilles', 'Sr. Arthur Connan Doyle', 'Melhoramentos', '336', 'Antonio Carlos Vilela', '', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2021-03-18');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('Sherlock Holmes - O Vale do Terror', 'Sr. Arthur Connan Doyle', 'Melhoramentos', '326', 'Antonio Carlos Vilela', '', 'Lido', 'Diego', 'Fiction', 'pt-BR', '2021-03-18');
INSERT INTO books (Book_Title, Author, Publisher, Number_of_pages, Translator, Year_bought, Status, Owner, Categories, Language, Publisheddate) VALUES ('A morte e a morte de Quincas Berro Dágua', 'Jorge Amado', 'Record', '103', '', '', 'Lido', 'Hugo', 'Fiction', 'pt-BR', '2008-03-10');
